tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-container-low": "#faf3e9",
                "on-primary-container": "#fffbfa",
                "on-secondary-container": "#783d01",
                "on-error": "#ffffff",
                "on-secondary": "#ffffff",
                "background": "#fff8f0",
                "primary": "#914617",
                "tertiary": "#874c2e",
                "on-primary": "#ffffff",
                "surface-container": "#f4ede3",
                "inverse-primary": "#ffb68f",
                "secondary-fixed-dim": "#ffb780",
                "surface-container-high": "#eee7dd",
                "surface-container-lowest": "#ffffff",
                "secondary-container": "#ffab69",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#ffdbcc",
                "surface-bright": "#fff8f0",
                "on-secondary-fixed-variant": "#6f3800",
                "error-container": "#ffdad6",
                "on-primary-fixed-variant": "#773302",
                "surface-variant": "#e8e2d8",
                "on-surface-variant": "#54433a",
                "primary-fixed": "#ffdbca",
                "primary-container": "#b05e2d",
                "surface-tint": "#954919",
                "outline-variant": "#dac1b6",
                "outline": "#877369",
                "primary-fixed-dim": "#ffb68f",
                "inverse-on-surface": "#f7f0e6",
                "surface-dim": "#e0d9d0",
                "secondary": "#8e4e14",
                "on-error-container": "#93000a",
                "on-secondary-fixed": "#2f1400",
                "on-tertiary-fixed": "#351000",
                "on-tertiary-container": "#fffbfa",
                "on-surface": "#1e1b16",
                "tertiary-container": "#a46444",
                "secondary-fixed": "#ffdcc4",
                "on-tertiary-fixed-variant": "#6e381c",
                "on-background": "#1e1b16",
                "inverse-surface": "#33302a",
                "tertiary-fixed-dim": "#ffb693",
                "surface-container-highest": "#e8e2d8",
                "surface": "#fff8f0",
                "on-primary-fixed": "#331100",
                "error": "#ba1a1a"
            },
            fontFamily: {
                "headline": ["Noto Serif"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
        },
    },
};